---
language: python
python:
  - "2.7"
services: docker

env:
  global:
    - ANSIBLE_VERSION=2.9.11
    - PLATFORM="linux_x86_64"
  matrix:
    - DOCKERFILE="Dockerfile.centos" IMAGE="centos:7"
    # - DOCKERFILE="Dockerfile.centos" IMAGE="centos:8"
    # - DOCKERFILE="Dockerfile.debian" IMAGE="debian:jessie-slim"
    # - DOCKERFILE="Dockerfile.debian" IMAGE="debian:stretch-slim"
    # - DOCKERFILE="Dockerfile.debian" IMAGE="debian:buster-slim"
    - DOCKERFILE="Dockerfile.debian" IMAGE="ubuntu:16.04"
    # - DOCKERFILE="Dockerfile.debian" IMAGE="ubuntu:18.04"
    # - DOCKERFILE="Dockerfile.debian" IMAGE="ubuntu:20.04"

script:
  - ./build-bundle.py "$ANSIBLE_VERSION"
  - .travis/test.sh

jobs:
  include:
    - stage: lint
    - script:
        - pip install tox
        - tox -e flake8
    - stage: deploy
      script: echo "Deploying to GitHub releases ..."
      env: DOCKERFILE="" IMAGE=""
